### PR TITLE
add mocha as devDependency to lower package size

### PR DESCRIPTION
**Pull request by TheChickenNagget**

### CODE REVIEW

**Comment by lwillmeth** [comment]
Moving mocha to devDependencies is like a good change, but why install mocha in npm test?

**Comment by boutell** [comment]
Yeah, that is superfluous. Just move it to devDependencies.

**Comment by TheChickenNagget** [comment]
i like this package but i hate that it uses "mocha" that has another 24 Dependencies 
https://www.npmjs.com/package/mocha?activeTab=dependencies

**Comment by TheChickenNagget** [comment]
> Moving mocha to devDependencies is a good change, but why install mocha in npm test?

Alright i removed the npm install in test script

**Pull request merged**
